### ISSUE TITLE
Add travis support

### ISSUE THREAD

**Issue by halink0803** [KyberNetwork/widget-woocommerce#10]
Currently the plugin features is almost complete and stable. However, there is no test added as well as any CI service integrated yet (travis ci service is enabled already, but no config set). The tests and CI will help to maintain the plugin logic for future development.

Any support is welcome. Feel free to fork and create a pull request for the plugin. You can take https://github.com/KyberNetwork/widget-woocommerce/pull/8 PR as a reference.

The checklist for the PR should have:

- [ ] add config .travis.yml
- [ ] enable coverage report

**Comment by olivernybroe** [comment]
Maybe split this into two issues? One for CI and one for tests.

**Comment by halink0803** [comment]
@olivernybroe Yes, possible. Let me split tests to another issues.
