### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by halink0803** [KyberNetwork/widget-woocommerce#11]
Currently the plugin features is almost complete and stable. However, there is no test added. The tests will help to maintain the plugin logic for future development.

Any support is welcome. Feel free to fork and create a pull request for the plugin. You can take #8 PR as a reference.

The checklist for the PR should have:

- [ ] add tests (folder tests)

**Comment by dangenendt** [comment]
Am i right that you mean everything in "includes/"-Folder?

**Comment by halink0803** [comment]
> Am i right that you mean everything in "includes/"-Folder?

@dangenendt actually mostly logic stay in `class-woo-kyber-payment-gateway.php`, so I would satisfy if that class is tested. The others is great to have.

**Comment by dangenendt** [comment]
Ok, let me see what i can do.

**Comment by halink0803** [comment]
@dangenendt Thank you for looking into the code. The plugin need some Wordpress and Woocommerce background to understand and write tests.
