### ISSUE TITLE
Don't display Kyber Total on non-kyber transactions

### ISSUE THREAD

**Issue by companyhen** [KyberNetwork/widget-woocommerce#63]
It was hard to word the title for this, but basically only show the DAI/KNC/ETH amount if they choose Kyber payment at checkout.

For example, this PayPal checkout shows "DAI" amount under the total USD price:

![screen shot 2019-02-15 at 11 00 53](https://user-images.githubusercontent.com/1679107/52868441-5c0be800-3111-11e9-9a74-3205eb4827a7.png)

I think it would just need a simple if statement

**Comment by halink0803** [comment]
@companyhen I also saw that the DAI price currently does not include shipping fee. Should we upgrade including shipping fee as well? Anw, thank you for your feedback. This bug(feature) should be fixed in next release (intend to release in early of March)

**Comment by halink0803** [comment]
Kyber Total is removed from https://github.com/KyberNetwork/widget-woocommerce/releases/tag/v0.2.1. Close this issue.
